version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: chat-agents-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: chat-agents-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat-agents-db
      POSTGRES_USER: chat-agents-user
      POSTGRES_PASSWORD: chat-agents-password
    volumes:
      - chatAgents:/var/lib/postgresql/data

volumes:
  chatAgents:
